name: Build multi-platform Docker Image

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Auto Update Version and Release"]  # Must match the exact `name:` in autorelease.yml
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    if: |
      github.event_name != 'workflow_run' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version parts
        id: semver
        run: |
          # Remove leading refs/tags/v or refs/tags/V
          RAW_TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${RAW_TAG#v}"
          SHORT_VERSION=$(echo "$VERSION" | cut -d. -f1-3)

          echo "tag=$VERSION" >> "$GITHUB_OUTPUT"
          echo "short=$SHORT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/shall0pass/actualtap
          tags: |
            type=raw,value=${{ steps.semver.outputs.tag }}
            type=raw,value=${{ steps.semver.outputs.short }}
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
